/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PostCheckoutRouteImport } from './routes/post-checkout'
import { Route as SFacilityRouteImport } from './routes/s.$facility'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PostCheckoutRoute = PostCheckoutRouteImport.update({
  id: '/post-checkout',
  path: '/post-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SFacilityRoute = SFacilityRouteImport.update({
  id: '/s/$facility',
  path: '/s/$facility',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/post-checkout': typeof PostCheckoutRoute
  '/s/$facility': typeof SFacilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/post-checkout': typeof PostCheckoutRoute
  '/s/$facility': typeof SFacilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/post-checkout': typeof PostCheckoutRoute
  '/s/$facility': typeof SFacilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/post-checkout' | '/s/$facility'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/post-checkout' | '/s/$facility'
  id: '__root__' | '/' | '/dashboard' | '/post-checkout' | '/s/$facility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PostCheckoutRoute: typeof PostCheckoutRoute
  SFacilityRoute: typeof SFacilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-checkout': {
      id: '/post-checkout'
      path: '/post-checkout'
      fullPath: '/post-checkout'
      preLoaderRoute: typeof PostCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$facility': {
      id: '/s/$facility'
      path: '/s/$facility'
      fullPath: '/s/$facility'
      preLoaderRoute: typeof SFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PostCheckoutRoute: PostCheckoutRoute,
  SFacilityRoute: SFacilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
