/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PostCheckoutRouteImport } from './routes/post-checkout'
import { Route as SurveyFacilityRouteImport } from './routes/survey.$facility'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PostCheckoutRoute = PostCheckoutRouteImport.update({
  id: '/post-checkout',
  path: '/post-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyFacilityRoute = SurveyFacilityRouteImport.update({
  id: '/survey/$facility',
  path: '/survey/$facility',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/post-checkout': typeof PostCheckoutRoute
  '/survey/$facility': typeof SurveyFacilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/post-checkout': typeof PostCheckoutRoute
  '/survey/$facility': typeof SurveyFacilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/post-checkout': typeof PostCheckoutRoute
  '/survey/$facility': typeof SurveyFacilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/post-checkout' | '/survey/$facility'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/post-checkout' | '/survey/$facility'
  id: '__root__' | '/' | '/admin' | '/post-checkout' | '/survey/$facility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PostCheckoutRoute: typeof PostCheckoutRoute
  SurveyFacilityRoute: typeof SurveyFacilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-checkout': {
      id: '/post-checkout'
      path: '/post-checkout'
      fullPath: '/post-checkout'
      preLoaderRoute: typeof PostCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$facility': {
      id: '/survey/$facility'
      path: '/survey/$facility'
      fullPath: '/survey/$facility'
      preLoaderRoute: typeof SurveyFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PostCheckoutRoute: PostCheckoutRoute,
  SurveyFacilityRoute: SurveyFacilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
